# Generated by Django 5.2.5 on 2025-08-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_alter_historialreparacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(verbose_name='Año'),
        ),
    ]
